image: node:18-alpine

stages:
  - build
  - deploy

before_script:
  - npm install --frozen-lockfile --check-files --non-interactive

build:
  stage: build
  script:
    - npm run build
    - mkdir -p public
    - cp -r dist/* public/
  artifacts:
    paths:
      - public

pages:
  stage: deploy
  script:
    - echo 'Deploying to GitLab Pages'
  artifacts:
    paths:
      - public
  only:
    - main
